version: '3.8'

services:
  users-api:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=users_db
      - JWT_SECRET=your-super-secret-key-change-in-production
      - JWT_ACCESS_TTL=3600
      - JWT_REFRESH_TTL=604800
      - SERVER_PORT=8001
      - SERVER_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - INTERNAL_API_KEY=internal-secret-key
    depends_on:
      - mysql
      - redis
    networks:
      - users-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=users_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - users-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - users-network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  users-network:
    driver: bridge